"use client";
import { useState } from "react";
const steps=["Evidence review","Evidence graph","SBOM impact","Incident draft","Dossier"];
export function EvidenceDemo(){
 const[step,setStep]=useState(0);const[approved,setApproved]=useState(false);const[upload,setUpload]=useState("Choose a PDF or CycloneDX JSON file");
 async function uploadArtifact(file?:File){if(!file)return;setUpload("Validating and storing…");try{const body=new FormData();body.set("file",file);const response=await fetch("/api/v1/artifacts",{method:"POST",body});const data=await response.json();if(!response.ok)throw new Error(data.error);setUpload(`Stored · SHA-256 ${data.artifact.sha256.slice(0,12)}…`)}catch(error){setUpload(error instanceof Error?error.message:"Upload failed")}}
 return <main><aside><div className="brand"><span>CE</span><div>CRA Evidence OS<small>Build Week demo</small></div></div><nav aria-label="Demo workflow">{steps.map((s,i)=><button key={s} className={step===i?"active":""} onClick={()=>setStep(i)}><b>0{i+1}</b>{s}</button>)}</nav><div className="guardrail">AI assists. People decide.<small>This measures evidence readiness—not legal compliance.</small></div></aside>
 <section className="shell"><header><div><small>AEGIS LABS / PRODUCTS</small><h1>AegisEdge Gateway <em>v2.3</em></h1></div><div className="score"><b>{approved?78:64}%</b><span>Evidence readiness</span></div></header>
 {step===0&&<article><div className="eyebrow">EVIDENCE INBOX · 1 NEEDS REVIEW</div><h2>Review an AI-grounded claim</h2><p>GPT-5.6 extracted a candidate statement. Compare it with the exact source before deciding.</p><label className="uploader">UPLOAD EVIDENCE<input aria-label="Upload evidence PDF or JSON" type="file" accept="application/pdf,application/json,.json" onChange={e=>uploadArtifact(e.target.files?.[0])}/><span>{upload}</span></label><div className="split"><section className="source"><label>ORIGINAL SOURCE · PAGE 4</label><h3>AegisEdge security architecture</h3><p>“All administrative traffic is protected using <mark>mutual TLS 1.3. Device identities are provisioned during manufacturing and rotated every 90 days.</mark> Failed authentication attempts are rate limited and recorded.”</p><footer>architecture-v2.3.pdf · SHA-256 7f3a…91c2</footer></section><section className="suggestion"><label>GPT-5.6 SUGGESTION · SCHEMA VALID</label><h3>Secure administrative communications</h3><p>AegisEdge Gateway protects administrative traffic with mutual TLS 1.3 and rotates provisioned device identities every 90 days.</p><dl><div><dt>Source</dt><dd>Page 4 · paragraph 2</dd></div><div><dt>Confidence</dt><dd>0.96</dd></div><div><dt>Status</dt><dd className={approved?"ok":"warn"}>{approved?"APPROVED":"NEEDS REVIEW"}</dd></div></dl><div className="actions"><button className="reject" onClick={()=>setApproved(false)}>Reject</button><button className="approve" onClick={()=>setApproved(true)}>Approve claim</button></div></section></div></article>}
 {step===1&&<article><div className="eyebrow">EVIDENCE GRAPH</div><h2>Every claim has a verifiable lineage</h2><div className="graph"><div>CRA REQUIREMENT<small>Annex I Part I (3)(d)</small></div><i>→</i><div className={approved?"good":"pending"}>CLAIM<small>{approved?"Approved by M. Chen":"Needs review"}</small></div><i>→</i><div>SOURCE FRAGMENT<small>Page 4 · paragraph 2</small></div><i>→</i><div>ARTIFACT<small>architecture-v2.3.pdf</small></div></div><p className="note">Approval is append-only and records reviewer, source version, timestamp and model run.</p></article>}
 {step===2&&<article><div className="eyebrow">SBOM DELTA · VERSION 2.3 → 2.4</div><h2>One component changed. Two claims need attention.</h2><div className="delta"><b>openssl</b><del>3.0.12</del><span>→</span><ins>3.0.14</ins><strong>UPDATED</strong></div><div className="cards"><div><span className="stale">STALE</span><h3>Secure administrative communications</h3><p>Linked through the TLS runtime dependency.</p></div><div><span className="stale">STALE</span><h3>Cryptographic update policy</h3><p>Evidence references the previous component snapshot.</p></div><div><span className="ok">CURRENT</span><h3>Access logging</h3><p>No graph path to the changed component.</p></div></div></article>}
 {step===3&&<article><div className="eyebrow">INCIDENT WORKSHEET · HUMAN REVIEW REQUIRED</div><h2>24h / 72h reporting facts, prepared—not submitted</h2><div className="worksheet"><div><label>Product</label><b>AegisEdge Gateway 2.3</b></div><div><label>Awareness time</label><b>2026-07-19 08:15 UTC</b></div><div><label>Incident summary</label><b>Authentication bypass under investigation</b></div><div><label>Exploitation observed</label><b className="warn">Unknown · confirmation required</b></div></div><p className="note">No ENISA API call is made. Export is copy-ready and requires explicit human submission.</p></article>}
 {step===4&&<article><div className="eyebrow">ANNEX VII MINI-DOSSIER</div><h2>A reproducible package with integrity metadata</h2><div className="manifest"><div><b>technical-dossier.pdf</b><code>SHA-256 in manifest</code></div><div><b>evidence-index.json</b><code>Approved source lineage</code></div><div><b>sbom.cdx.json</b><code>CycloneDX 1.6</code></div><div><b>manifest.json</b><code>4 files · DRAFT</code></div></div><div className="actions"><a className="reject download" href="/demo-export/technical-dossier.pdf" download>Download PDF</a><a className="approve download" href="/demo-export/aegisedge-annex-vii-draft.zip" download>Download ZIP package</a></div><p className="note">DRAFT — NOT APPROVED. Stale or unsupported claims remain visibly flagged.</p></article>}
 <footer className="stepper"><span>Demo workflow</span><b>{step+1} / {steps.length}</b><button disabled={step===steps.length-1} onClick={()=>setStep(Math.min(steps.length-1,step+1))}>Next step →</button></footer></section></main>
}
